import { Department, Professor, Course } from '@/types';

export const mockDepartments: Department[] = [
  { id: '1', code: 'COMM', name: 'Communication', fullName: 'Communication & Media Department' },
  { id: '2', code: 'ARTS', name: 'Arts', fullName: 'Arts Department' },
  { id: '3', code: 'COGS', name: 'Cognitive Science', fullName: 'Cognitive Science Department' },
  { id: '4', code: 'CSCI', name: 'Computer Science', fullName: 'Computer Science Department' },
  { id: '5', code: 'MATH', name: 'Mathematics', fullName: 'Mathematics Department' },
  { id: '6', code: 'PHYS', name: 'Physics', fullName: 'Physics Department' },
  { id: '7', code: 'CHEM', name: 'Chemistry', fullName: 'Chemistry Department' },
  { id: '8', code: 'BIOL', name: 'Biology', fullName: 'Biology Department' },
  { id: '9', code: 'ECON', name: 'Economics', fullName: 'Economics Department' },
  { id: '10', code: 'PSYC', name: 'Psychology', fullName: 'Psychology Department' },
  { id: '11', code: 'PHIL', name: 'Philosophy', fullName: 'Philosophy Department' },
  { id: '12', code: 'HIST', name: 'History', fullName: 'History Department' },
];

export const mockProfessors: Professor[] = [
  {
    id: '1',
    name: 'Barbara Cutler',
    firstName: 'Barbara',
    lastName: 'Cutler',
    department: 'Computer Science',
    departmentCode: 'CSCI',
    rating: 3.3,
    difficulty: 3.0,
    wouldTakeAgain: 65,
    numRatings: 45,
    email: 'cutler@cs.rpi.edu',
    officeLocation: 'Lally 305',
  },
  {
    id: '2',
    name: 'John Smith',
    firstName: 'John',
    lastName: 'Smith',
    department: 'Communication',
    departmentCode: 'COMM',
    rating: 4.2,
    difficulty: 2.5,
    wouldTakeAgain: 85,
    numRatings: 30,
    email: 'smithj@rpi.edu',
  },
  {
    id: '3',
    name: 'Jane Doe',
    firstName: 'Jane',
    lastName: 'Doe',
    department: 'Arts',
    departmentCode: 'ARTS',
    rating: 4.5,
    difficulty: 2.0,
    wouldTakeAgain: 90,
    numRatings: 25,
    email: 'doej@rpi.edu',
  },
  // Add more mock professors as needed
];

export const mockCourses: Course[] = [
  {
    id: '1',
    code: 'CSCI 1100',
    name: 'Computer Science I',
    department: 'Computer Science',
    departmentCode: 'CSCI',
    description: 'Introduction to computer programming and problem solving',
    credits: 4,
    difficulty: 3.2,
    prerequisites: [],
    professors: ['Barbara Cutler'],
  },
  {
    id: '2',
    code: 'COMM 2400',
    name: 'Media Studies',
    department: 'Communication',
    departmentCode: 'COMM',
    description: 'Introduction to media theory and analysis',
    credits: 3,
    difficulty: 2.5,
    prerequisites: [],
    professors: ['John Smith'],
  },
  {
    id: '3',
    code: 'ARTS 1010',
    name: 'Introduction to Studio Arts',
    department: 'Arts',
    departmentCode: 'ARTS',
    description: 'Fundamentals of visual arts and design',
    credits: 3,
    difficulty: 2.0,
    prerequisites: [],
    professors: ['Jane Doe'],
  },
  // Add more mock courses as needed
];