import os
import sys

# Get the directory where the Python script itself is located
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# --- Configuration Update ---

# 1. DEFINE THE PROJECT ROOT RELATIVE TO THE SCRIPT
# Example: If MyProject is one level up (..) and then down into MyProjectName
PROJECT_ROOT_DIR = os.path.join('PathFinder') 
# You need to adjust '..', 'MyProject' to match your actual structure. 
# For example, if it's two folders away, it might be: os.path.join(SCRIPT_DIR, '..', '..', 'MyProject')

# 2. Use the PROJECT_ROOT_DIR for all subsequent paths
ASSETS_DIR = os.path.join(PROJECT_ROOT_DIR, 'assets', 'images', 'imgs') 
OUTPUT_FILE = os.path.join(PROJECT_ROOT_DIR, 'components', 'ImageMap.ts') #PathFinder\assets\images\imgs

# 3. CRUCIAL: Re-calculate the REQUIRE_PATH_PREFIX
# This path MUST be the path from OUTPUT_FILE (inside the project) to ASSETS_DIR (inside the project).
# This path is relative to the internal project structure, NOT the script location.
# If OUTPUT_FILE is in 'MyProject/src/constants' and ASSETS_DIR is in 'MyProject/assets/images'
REQUIRE_PATH_PREFIX = '../assets/images/imgs/'

ALLOWED_EXTENSIONS = ('.png', '.jpg', '.jpeg', '.gif', '.webp')
# ----------------------------

# ... rest of your generate_map() function ...
# ---------------------

def generate_map():
    # 1. Read the list of files and filter
    try:
        files = os.listdir(ASSETS_DIR)
        image_files = [f for f in files if os.path.splitext(f.lower())[1] in ALLOWED_EXTENSIONS]
    except FileNotFoundError:
        print(f"❌ Error: Asset directory not found at {ASSETS_DIR}")
        return

    # Prepare file content strings
    type_union = []
    map_entries = []

    for file in image_files:
        # Get the image name without the extension
        image_name = os.path.splitext(file)[0]
        
        # Add to the TypeScript Union Type (e.g., "'apple'")
        type_union.append(f"  | '{image_name}'")
        
        # Add to the map entry (e.g., "'apple': require('../../assets/images/apple.png'),")
        map_entries.append(f"  '{image_name}': require('{REQUIRE_PATH_PREFIX}{file}'),")

    # 2. Assemble the TypeScript content
    type_content = "\n".join(type_union)

    content = f"""// src/constants/ImageMap.ts
// THIS FILE IS AUTOMATICALLY GENERATED BY generate_image_map.py. DO NOT EDIT MANUALLY.

// Define the Union Type of all available image keys for type safety
export type ImageKey = 
{type_content};

// Define the type for the image source (a number, which is what require() returns)
type ImageSource = number;

// Define and export the constant map
export const IMAGE_MAP: Record<ImageKey, ImageSource> = {{
{'\n'.join(map_entries)}
}};
"""

    # 3. Write the content to the output file
    try:
        # Ensure the output directory exists
        os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
        
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"✅ Successfully generated image map at: {OUTPUT_FILE}")
        print(f"   Total images included: {len(image_files)}")
        
    except Exception as e:
        print(f"❌ Failed to write image map file: {e}")


if __name__ == "__main__":
    generate_map()